### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by saihum** [rajkumardusad/IP-Tracer#10]
For the second time
![IMG_20200718_144024](https://user-images.githubusercontent.com/54665629/87849828-7b620280-c90d-11ea-8be4-5271a96e8738.jpg)

**Comment by rajkumardusad** [comment]
Hey @saihum if you know the exec format so please tell me the valid exec format

**Comment by saihum** [comment]
> Hey @saihum if you know the exec format so please tell me the valid exec format

I don't know anything beside that photo.. please check the photo

**Comment by rajkumardusad** [comment]
I don't know which terminal you are using, but this tool works in termux, ubuntu, kali and so on.
