### ISSUE TITLE
sh install command not found

### ISSUE THREAD

**Issue by Xenoy017** [rajkumardusad/IP-Tracer#12]
all the other commands worked like they were supposed to but when I did the sh install and ./install it would say:
./install: line 16: apt-get: command not found
./install: line 17: apt: command not found
./install: line 18: apt-get: command not found
./install: line 19: apt-get: command not found
./install: line 31: php: command not found
OR
install: line 16: apt-get: command not found
install: line 17: apt: command not found
install: line 18: apt-get: command not found
install: line 19: apt-get: command not found
install: line 31: php: command not found

**Comment by rajkumardusad** [comment]
Hey @Xenoy017 which system your using?

**Comment by Xenoy017** [comment]
i am using a windows 10 laptop

**Comment by rajkumardusad** [comment]
Hey @Xenoy017 may be this tool not works in windows system?

**Comment by Xenoy017** [comment]
possibly i guess
