### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by j-dogcoder** [rajkumardusad/IP-Tracer#17]
Hi there, I am a developer and I am building a tool called Blackeye 2.0. I was looking to incorporate your project into ours. I have a very small team but would be happy to help migrate. You can contact me via email at j-dogcoder@gmail.com or through discord on our server at [https://discord.gg/dMhTPdw2bh](https://discord.gg/dMhTPdw2bh). 

You can find our project at [https://github.com/j-dogcoder/Blackeye-2.0](https://github.com/j-dogcoder/Blackeye-2.0)

**Comment by Ru531** [comment]
Hi I am rubayeth ahemed I am agree to work with you

**Comment by j-dogcoder** [comment]
Hi! How would you like to go about this? I can give you access to my repo if you want to integrate it there.

**Comment by rajkumardusad** [comment]
> Hi there, I am a developer and I am building a tool called Blackeye 2.0. I was looking to incorporate your project into ours. I have a very small team but would be happy to help migrate. You can contact me via email at [j-dogcoder@gmail.com](mailto:j-dogcoder@gmail.com) or through discord on our server at https://discord.gg/dMhTPdw2bh.
> 
> You can find our project at https://github.com/j-dogcoder/Blackeye-2.0

Yes sure
