### ISSUE TITLE
Ip-tracer not working

### ISSUE THREAD

**Issue by Jashim871** [rajkumardusad/IP-Tracer#18]
It's not working please fix it .
Thank you

**Comment by rajkumardusad** [comment]
Hey @Jashim871 what is the error?

**Comment by Jashim871** [comment]
I use your tools lots of time but currently it's not  working , i am trying
for tow days

**Comment by rajkumardusad** [comment]
Okay but if you tell me the error then i will solve the issue.

**Comment by Jashim871** [comment]
I send you a screenshot you can see that , it's the problem i am facing

**Comment by rajkumardusad** [comment]
Sorry but, i can't find any screenshot.

**Comment by Jashim871** [comment]
That is

**Comment by rajkumardusad** [comment]
Please attach screenshot.
