### ISSUE TITLE
Installation Fail MacOS

### ISSUE THREAD

**Issue by RocketNinja15** [rajkumardusad/IP-Tracer#21]
rm: /usr/bin/trace: Operation not permitted
mv: rename modules/ip-tracer to /usr/bin/ip-tracer: Operation not permitted
override rwxr-xr-x  root/wheel for /usr/bin/trace? (y/n [n]) y
mv: rename modules/trace to /usr/bin/trace: Operation not permitted
chmod: /usr/bin/ip-tracer: No such file or directory
mkdir: /usr/share/IP-Tracer/: Operation not permitted
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

      _ ____    _
     (_)  _ \  | |_ _ __ __ _  ___ ___ _ __
     | | |_) | | __| '__/ _` |/ __/ _ \ '__|
     | |  __/  | |_| | | (_| | (_|  __/ |
     |_|_|      \__|_|  \__,_|\___\___|_|

    }--------------------------------------{
 }------------- Track IPLocation -------------{
    }--------------------------------------{

  Sorry IP-Tracer is not installed !!!

**Comment by rajkumardusad** [comment]
Yes may be some issue in mac because we have tested in macOS. can you solve this issue?
