### ISSUE TITLE
Ip tracer

### ISSUE THREAD

**Issue by yubrajjj** [rajkumardusad/IP-Tracer#22]
It is showing us offline when we trace other ip but working normally when we are tracing our own ip

**Comment by JosephCordero** [comment]
How are you getting it to work it's asking me to log in and I've done that but I keep getting this error "remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/thelinuxchoice/saycheese/' "

**Comment by rajkumardusad** [comment]
Hey @JosephCordero clone proper link it will never ask username and password.
`$ git clone https://github.com/rajkumardusad/IP-Tracer`
It will work.

**Comment by JosephCordero** [comment]
OMG I'm sorry I posted that under the wrong GitHub my apologies

**Comment by JosephCordero** [comment]
How come when I try to use the example it says this " Sorry unable to track your IP Address !!!
 Check your Network connection !!
 If you are Online then check your IP Addres "

**Comment by 7hruv** [comment]
![Screenshot_20210808-173713_Termux](https://user-images.githubusercontent.com/88592969/128631432-5f42a384-2b27-4bbc-bad2-a47a45319422.jpg)
It's showing I can trace my ip but not that i want
