### ISSUE TITLE
IP-Tracer

### ISSUE THREAD

**Issue by seenu411** [rajkumardusad/IP-Tracer#24]
There's is an showing password for use this tool.

So what's what's the matter?
Can u tell m pls?

**Comment by rajkumardusad** [comment]
Hey @seenu411 this tool never ask any username and password, please clone proper url.
`git clone https://github.com/rajkumardusad/IP-Tracer`

**Comment by seenu411** [comment]
> Hey @seenu411 this tool never ask any username and password, please clone proper url.
> `git clone https://github.com/rajkumardusad/IP-Tracer`

I copy amd paste this link but they asking for username and password have u any solution pls tell m?

**Comment by rajkumardusad** [comment]
![IMG_20210131_085537](https://user-images.githubusercontent.com/32831684/106373692-23b75000-63a2-11eb-86d8-5b1dde15d2e7.jpg)

I have tested it works fine.
