### ISSUE TITLE
Totally wrong Location

### ISSUE THREAD

**Issue by Faizrgb** [rajkumardusad/IP-Tracer#47]
Either explain this tool property or take it down.. this tools shows wrong location. And no u can't do anything with this tool.

**Comment by dgsdoug** [comment]
> Either explain this tool property or take it down.. this tools shows wrong location. And no u can't do anything with this tool.

**Comment by rajkumardusad** [comment]
Hey @Faizrgb this tool or ip geolocation tools doesn't show live location of client, they only show client isp details.
