### ISSUE TITLE
Problems installing in archlinux

### ISSUE THREAD

**Issue by popj951203** [rajkumardusad/IP-Tracer#54]
i  cant run the install script on archlinux, even after installing php and php5 dependencies manually

**Comment by rajkumardusad** [comment]
What is the error you are getting?

**Comment by popj951203** [comment]
There is no prompt, just says that ip Tracer was Not installed and erases all the directory

**Comment by rajkumardusad** [comment]
What is the version of your arch linux?

**Comment by popj951203** [comment]
2022.06.01 release, just installed 2day
php 8.1.6-1 and php56 5.6.40-2

**Comment by rajkumardusad** [comment]
Ok there might be some issue, we will fix it soon. Your can tryout other tools they might work for you.

**Comment by popj951203** [comment]
Thank You, i'll be waiting for this
